[server]
headless = true
enableCORS = false

[theme]
base = "light"
primaryColor = "#7C3AED"
backgroundColor = "#F1F5F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"
